version: '3.7'

services:
  redis:
    image: redis:7.2
    container_name: local_redis
    ports:
      - 6379:6379
    volumes:
      - ~/container/redis/data:/data
    restart: always
    labels:
      - "name=redis"
      - "mode=standalone"
    command: redis-server --port 6379